apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: charles-trigger-template
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
    default: master
  - name: git-repo-name
    description: The name of the deployment to be created / patched 

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: charles-pipeline-$(tt.params.git-revision)
    spec:
      params:
        - name: APP_NAME
          value: front-end-mesh
        - name: GIT_REPO
          value: 'https://github.com/microservicePOC1/frontEndMesh'
        - name: GIT_REVISION
          value: ''
        - name: IMAGE_NAME
          value: 'image-registry.openshift-image-registry.svc:5000/front-end-new/front-end-mesh'
        - name: PATH_CONTEXT
          value: .
      pipelineRef:
        name: front-end-mesh
      serviceAccountName: pipeline
      workspaces:
        - name: workspace
          volumeClaimTemplate:
            metadata:
              creationTimestamp: null
              labels:
                tekton.dev/pipeline: front-end-mesh
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
